### ISSUE TITLE
Ajout d'un bouton sur le message de création d'alerte permettant d'accéder directement aux trains

### ISSUE THREAD

**Issue by r33int** [leonekmi/MaxPing#6]
**Quel est le problème que votre fonctionnalité résout ?**
Cela permettrait de gagner du temps lorsqu'on veut voir les trains disponibles sur une alerte qu'on vient de créer, sans avoir à rechercher à nouveau l'alerte.

**Quelle serait la solution à apporter ?**
Ajouter un bouton sur le message indiquant qu'une alerte a été créé avec succès permettant d'accéder directement à la liste des trains de l'alerte en question.

**Comment by leonekmi** [comment]
C'est fait !
